# Generated by Django 6.1 on 2026-08-24 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='elections.schoolelection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ballot',
                'verbose_name_plural': 'Ballots',
                'db_table': 'voting_ballot',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VoteChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anonymized', models.BooleanField(default=False)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='voting.ballot')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.schoolposition')),
            ],
            options={
                'verbose_name': 'Vote Choice',
                'verbose_name_plural': 'Vote Choices',
                'db_table': 'voting_votechoice',
                'ordering': ['position__display_order'],
                'unique_together': {('ballot', 'position')},
            },
        ),
        migrations.CreateModel(
            name='VoteReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('receipt_hash', models.CharField(db_index=True, help_text='SHA-256 hash of receipt for verification', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='elections.schoolelection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote Receipt',
                'verbose_name_plural': 'Vote Receipts',
                'db_table': 'voting_votereceipt',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'election')},
            },
        ),
        migrations.AddField(
            model_name='ballot',
            name='receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ballot', to='voting.votereceipt'),
        ),
        migrations.CreateModel(
            name='AnonVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anon_votes', to='candidates.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anon_votes', to='elections.schoolelection')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anon_votes', to='elections.schoolposition')),
            ],
            options={
                'verbose_name': 'Anonymous Vote',
                'verbose_name_plural': 'Anonymous Votes',
                'db_table': 'voting_anonvote',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['election', 'position', 'candidate'], name='voting_anon_electio_432360_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_index', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voter_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('vote_data', models.JSONField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('current_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('validator_signature', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_blocks', to='elections.schoolelection')),
                ('vote_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_blocks', to='voting.votechoice')),
            ],
            options={
                'verbose_name': 'Vote Block',
                'verbose_name_plural': 'Vote Blocks',
                'db_table': 'voting_voteblock',
                'ordering': ['election_id', 'block_index'],
                'indexes': [models.Index(fields=['election', 'block_index'], name='voting_vote_electio_e32494_idx'), models.Index(fields=['election', 'voter_fingerprint'], name='voting_vote_electio_83e661_idx')],
                'constraints': [models.UniqueConstraint(fields=('election', 'block_index'), name='unique_vote_block_index_per_election')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ballot',
            unique_together={('user', 'election')},
        ),
    ]
