# Generated by Django 6.1 on 2026-08-24 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='party_logos/')),
                ('color', models.CharField(default='#0b6e3b', help_text='Hex color code for party branding', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'db_table': 'elections_party',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('max_candidates', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Position',
                'verbose_name_plural': 'School Positions',
                'db_table': 'elections_schoolposition',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('election_type', models.CharField(choices=[('university', 'University Student Council (USC)'), ('department', 'Department Election')], default='university', max_length=20)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_department', models.ForeignKey(blank=True, help_text='Department allowed to vote (only for Department Election type)', limit_choices_to={'program_type': 'department'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_elections', to='accounts.program', to_field='code')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Election',
                'verbose_name_plural': 'School Elections',
                'db_table': 'elections_schoolelection',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ElectionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_positions', to='elections.schoolelection')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_elections', to='elections.schoolposition')),
            ],
            options={
                'verbose_name': 'Election Position',
                'verbose_name_plural': 'Election Positions',
                'db_table': 'elections_electionposition',
                'ordering': ['order', 'position__display_order'],
                'unique_together': {('election', 'position')},
            },
        ),
    ]
